./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test1.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test2.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test3.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test4.ltl
echo "Reponse attendu : SAT"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test5.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test6.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test7.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test8.ltl
echo "Reponse attendu : SAT"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test10.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test11.ltl
echo "Reponse attendu : SAT"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test12.ltl
echo "Reponse attendu : SAT"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test13.ltl
echo "Reponse attendu : UnSat"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test14.ltl
echo "Reponse attendu : SAT"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test15.ltl
echo "Reponse attendu : SAT"
./check.native -m Tests/debug_tests/model1.fmc -ltl Tests/debug_tests/test16.ltl
echo "Reponse attendu : UnSat"