./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test1.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test2.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test3.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test4.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test5.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test6.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test7.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test8.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test9.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test10.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test11.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test13.ltl
./check.native -m Tests/tests_modele_simple/model.fmc -ltl Tests/tests_modele_simple/test14.ltl